[package]
name = "MacdDivergence"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3.0"
charming = { version = "0.3.1", features = ["ssr"] }
